### ISSUE TITLE
Need to specify Crystal version

### ISSUE THREAD

**Issue by jwoertink** [russ/listmonk#1]
https://github.com/russ/listmonk/blob/main/shard.yml

Because the shard.yml doesn't specify a Crystal version, it's default is `< 1.0.0`. This is technically fixed https://github.com/crystal-lang/shards/pull/493 but won't be released until the next shards release.... 

I'd recommend just doing `crystal: ">= 0.36.1"`

**Comment by russ** [comment]
Added here https://github.com/russ/listmonk/commit/b7408b8e49f68dc843617fc95573a6c7e658361c
